#!/bin/bash
#test script for Lab1

#fire up both server and client.do this only after a make myclient and make myserver have been run
myserver 3005&
myclient 127.0.0.1 3005
#now test all the functions i know to work
cat /etc/resolv.conf
cat hello
date 
df -h 
echo hello world
uname -a 
uptime 
who 
exit
